### PR TITLE
Winston 3

### PR DESCRIPTION
**Pull request by mgibeau**
This PR adds support for Winston 3 (#28). I bumped the version to 3.0.0 as I had to refactor and drop a bunch of options. I updated the tests but I haven't checked for backward compatibility...

Also in this update:
- Updated redis dependency
- Updated async dependency
- Requires NodeJS 8+

### CODE REVIEW

**Comment by yads** [comment]
Thanks for this. I can merge it, although it seems like the main maintainers of this project (the ones with npm push access) have abandoned this project. I would suggest creating your own fork of this project.

**Comment by mgibeau** [comment]
Sure, no problem, thanks for the follow up.

**Comment by binarymist** [comment]
What's the state of this project and/or your fork @mgibeau ?

**Comment by DABH** [comment]
Reopening this because @indexzero gave @mgibeau write access to this repo — so hopefully he can take over as the maintainer and get this working well for winston@3.  This PR should probably be merged — we need some starting point at least for a winston@3 version — though I have not taken a careful look at it.  If @mgibeau takes over then he should feel free to merge this and do whatever is necessary to keep this working well for winston@3 :) Thanks all!

**Comment by DABH** [comment]
And also @yads @mgibeau if you feel there is a npm release that should happen, mention me or indexzero, we will try to cut a release or give you access on npm.  Thanks!

**Comment by yads** [comment]
There have been several issues open asking for a new NPM release, but glad to see the project still being monitored, that's great news!

**Comment by DABH** [comment]
Yeah, hopefully with winston@3 becoming more stable now, we can give some new life to all the community transports, let's see :)  Asked indexzero regarding npm access so hopefully we see some new npm releases soon.

**Comment by binarymist** [comment]
Good work contributors!
It looks like the transport doesn't quite fit my requirements of pushing three (at this stage) types of data:

1. text message
2. integer message as a %
3. integer message as a bug count

All of which will be sent on three different channels minimum at different times, in the form of:

`{ id: update.timestamp, event: update.event, data: update.data }`

which is consumed by subscribbers converting the messages into server sent events (SSE) (AKA EventSource) to be sent to a CLI somewhere on the internet.

**Pull request merged**
