### PR TITLE
Fix redis error

### PR DESCRIPTION
**Pull request by Farenheith**
When Redis is having a unavailability error, from node 16 and over, the application can fall. With this fix, we prevent this

### CODE REVIEW

**Comment by DABH** [comment]
Hi @Farenheith , is this still needed?  Saw it got closed.  In any case, we probably don’t want the extra release stuff?  Not sure what that is.

**Comment by Farenheith** [comment]
Hello @DABH, I opened it by mistake. The PR was meant to be open in a fork that we use internally. The getSafeInstance that I used to solve the problem may not be the best approach as it adds a new dependency for you library, but I'm glad to create a PR for you lib trying to solve the problem in a better way.
Maybe wrapping the redis calls with a function like this:

```ts
export function dontWait(
	callback: () => Promise<unknown>,
	errorCallback?: (err: Error) => void,
): void {
	setImmediate(async () => {
		try {
			await callback();
		} catch (error) {
			errorCallback?.(error as Error);
		}
	});
}
```

Or maybe creating a proxy around the redis instance, implementing the same solution of get-safe-instance. What do you think?

**Comment by DABH** [comment]
Ah got it, no worries.  Yeah, I’d be open to a non-breaking change that adds some safeguards without adding a new dependency.  Open to further discussions on this!  Thanks!

**Comment by Farenheith** [comment]
@DABH I've just created a more reasonable pull request, if you want to take look, here it is: https://github.com/winstonjs/winston-redis/pull/45
Thank you for your attention!

**Pull request closed without merging**
